credentials:
  usernames:
    admin:
      email: admin@gmail.com
      name: admin
      password: admin123  # Must be hashed

cookie:
  expiry_days: 30
  name: my_cookie
  key: some_random_key

preauthorized:
  emails: []
